volumes:
  pg_data:
  static:
  media:
  frontend_build:

services:
  db:
    image: postgres:15
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    image: ashotvartan/foodgram_backend:latest
    env_file: .env
    volumes:
      - static:/app/static
      - media:/app/media
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/"]
      interval: 30s
      timeout: 10s
      retries: 3

  frontend:
    image: ashotvartan/foodgram_frontend:latest
    volumes:
      - frontend_build:/app/build
    command: ["sh", "-c", "cp -r /app/build/. /frontend_build/"]

  gateway:
    image: ashotvartan/foodgram_gateway:latest
    ports:
      - "9000:80"
    volumes:
      - static:/staticfiles
      - media:/media
      - frontend_build:/usr/share/nginx/html
    depends_on:
      - backend
      - frontend
