# Константы для проекта Foodgram

# Пользователи
EMAIL_MAX_LENGTH = 254
USERNAME_MAX_LENGTH = 150
FIRST_NAME_MAX_LENGTH = 150
LAST_NAME_MAX_LENGTH = 150

# Рецепты
RECIPE_NAME_MAX_LENGTH = 200
RECIPE_COOKING_TIME_MIN = 1
RECIPE_COOKING_TIME_MAX = 32767

# Теги
TAG_NAME_MAX_LENGTH = 50
TAG_SLUG_MAX_LENGTH = 50

# Ингредиенты
INGREDIENT_NAME_MAX_LENGTH = 100
INGREDIENT_MEASUREMENT_UNIT_MAX_LENGTH = 20

# Пагинация
PAGE_SIZE = 6

# Прочее
MAX_FILE_SIZE_MB = 10
