# Константы для проекта Foodgram

# Пользователи
EMAIL_MAX_LENGTH = 254
USERNAME_MAX_LENGTH = 150
FIRST_NAME_MAX_LENGTH = 150
LAST_NAME_MAX_LENGTH = 150
MAX_NAME_LENGTH = 150
MAX_USERNAME_LENGTH = 150
MAX_EMAIL_LENGTH = 254

# Рецепты
RECIPE_NAME_MAX_LENGTH = 200
RECIPE_COOKING_TIME_MIN = 1
RECIPE_COOKING_TIME_MAX = 32767
MIN_COOKING_TIME = 1
MAX_COOKING_TIME = 32767

# Теги
TAG_NAME_MAX_LENGTH = 50
TAG_SLUG_MAX_LENGTH = 50

# Ингредиенты
INGREDIENT_NAME_MAX_LENGTH = 100
INGREDIENT_MEASUREMENT_UNIT_MAX_LENGTH = 20
MIN_INGREDIENT_AMOUNT = 1
MAX_INGREDIENT_AMOUNT = 32767

# Пагинация
PAGE_SIZE = 6

# Прочее
MAX_FILE_SIZE_MB = 10
